steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/laver-backend:$COMMIT_SHA',
      '--build-arg', 'DB_NAME=$_DB_NAME',
      '--build-arg', 'DB_USER=$_DB_USER',
      '--build-arg', 'DB_PASSWORD=$_DB_PASSWORD',
      '--build-arg', 'DB_HOST=$_DB_HOST',
      '--build-arg', 'DB_PORT=$_DB_PORT',
      '--build-arg', 'ENVIRONMENT=$_ENVIRONMENT',
      '--build-arg', 'ALLOWED_CORS_ORIGINS_REGEX=$_ALLOWED_CORS_ORIGINS_REGEX',
      '.'
    ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/laver-backend:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'laver-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/laver-backend:$COMMIT_SHA'
      - '--region'
      - '$_REGION'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/laver-backend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: us-central1  # Default region, can be overridden
  _DB_NAME: laver  # Default values, can be overridden
  _DB_USER: laver
  _DB_PASSWORD: laver
  _DB_HOST: localhost
  _DB_PORT: '5432'
  _ENVIRONMENT: production 
